# Generated by Django 4.2.12 on 2024-09-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('username', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.TextField()),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('password', models.TextField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'db_table': 'sign_up',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
